Repository tiki/capture-receipt-capacitor, pull requests merged in 2023-10, with the labels that each got.

#332 fix: tests updates
  android/src/test/kotlin/com/mytiki/sdk/capture/receipt/capacitor/AccountTest.kt
  android/src/test/kotlin/com/mytiki/sdk/capture/receipt/capacitor/ScanTypeEnumTest.kt
Labels: fix, testing

#342 fix: remove callbacks onComplete
  src/callback/callback-mgr.ts
Labels: fix

#343 doc: documentation update
  android/src/main/kotlin/com/mytiki/sdk/capture/receipt/capacitor/CaptureReceipt.kt
  android/src/main/kotlin/com/mytiki/sdk/capture/receipt/capacitor/account/AccountCommon.kt
  android/src/main/kotlin/com/mytiki/sdk/capture/receipt/capacitor/email/Email.kt
  android/src/main/kotlin/com/mytiki/sdk/capture/receipt/capacitor/plugin/CaptureReceiptPlugin.kt
  android/src/main/kotlin/com/mytiki/sdk/capture/receipt/capacitor/plugin/req/ReqInitialize.kt
  android/src/main/kotlin/com/mytiki/sdk/capture/receipt/capacitor/plugin/req/ReqScan.kt
  android/src/main/kotlin/com/mytiki/sdk/capture/receipt/capacitor/retailer/Retailer.kt
Labels: docs

#408 Fix/ios/imap disabled
  ios/Plugin/CaptureReceipt.swift
  ios/Plugin/Email/Email.swift
  ios/Plugin/Plugin/CaptureReceiptPlugin.swift
  ios/Plugin/Plugin/Rsp/RspErroEnum.swift
Labels: fix

#414 Fix/ios logout
  ios/Plugin/CaptureReceipt.swift
  ios/Plugin/Email/Email.swift
  src/capture-receipt.ts
  src/plugin/req/req-account.ts
Labels: bug, fix

#412 Test/android/bug finding
  android/src/main/kotlin/com/mytiki/sdk/capture/receipt/capacitor/email/Email.kt
  android/src/main/kotlin/com/mytiki/sdk/capture/receipt/capacitor/retailer/Retailer.kt
  example/src/app.vue
  example/src/main.ts
Labels: chore
