Repository tiki/capture-receipt-capacitor, pull requests merged in 2023-09, with the labels that each got.

#179 Fix/android/physical receipt bug
  android/src/main/kotlin/com/mytiki/sdk/capture/receipt/capacitor/Physical.kt
  android/src/main/kotlin/com/mytiki/sdk/capture/receipt/capacitor/Retailer.kt
  android/src/main/kotlin/com/mytiki/sdk/capture/receipt/capacitor/rsp/RspScan.kt
  src/receipt-capture-plugin.ts
  src/receipt-capture-web.ts
  src/receipt-capture.ts
Labels: bug, fix, Android, Vue

#227 Fix/android/creating tests
  android/build.gradle
  android/src/androidTest/kotlin/com/mytiki/sdk/capture/receipt/capacitor/ReceiptCaptureTest.kt
  android/src/androidTest/kotlin/com/mytiki/sdk/capture/receipt/capacitor/fixtures/PluginCallBuilder.kt
  android/src/main/kotlin/com/mytiki/sdk/capture/receipt/capacitor/Email.kt
  android/src/test/kotlin/com/mytiki/sdk/capture/receipt/capacitor/AccountCommonTest.kt
  android/src/test/kotlin/com/mytiki/sdk/capture/receipt/capacitor/AccountTest.kt
  android/src/test/kotlin/com/mytiki/sdk/capture/receipt/capacitor/AccountTypeEnumTest.kt
  android/src/test/kotlin/com/mytiki/sdk/capture/receipt/capacitor/EmailEnumTest.kt
  android/src/test/kotlin/com/mytiki/sdk/capture/receipt/capacitor/RetailerEnumTest.kt
  android/src/test/kotlin/com/mytiki/sdk/capture/receipt/capacitor/ScanTypeEnumTest.kt
Labels: testing, Android

#229 Update the API for capacitor plugin.
  .github/workflows/release.yml
Labels: Android

#245 Retailer and Physical working
  ScanTypeEnum.swift
  example/ios/App/App.xcodeproj/project.pbxproj
  example/src/main.ts
  ios/Plugin.xcodeproj/project.pbxproj
  ios/Plugin/Src/Mytiki/Sdk/Capture/Receipt/ReceiptCapture.swift
  ios/Plugin/Src/Mytiki/Sdk/Capture/Receipt/Req/ReqScan.swift
  ios/Plugin/Src/Mytiki/Sdk/Capture/Receipt/Retailer.swift
Labels: iOS

#249 feature poc google sign in
  android/src/androidTest/kotlin/com/mytiki/sdk/capture/receipt/capacitor/ReceiptCaptureTest.kt
  android/src/main/kotlin/com/mytiki/sdk/capture/receipt/capacitor/Account.kt
  android/src/main/kotlin/com/mytiki/sdk/capture/receipt/capacitor/Email.kt
  android/src/main/kotlin/com/mytiki/sdk/capture/receipt/capacitor/ReceiptCapture.kt
  android/src/main/kotlin/com/mytiki/sdk/capture/receipt/capacitor/ReceiptCapturePlugin.kt
  android/src/main/kotlin/com/mytiki/sdk/capture/receipt/capacitor/req/ReqInitialize.kt
  example/android/build.gradle
  example/android/variables.gradle
  example/package-lock.json
  example/src/main.ts
  package-lock.json
  src/receipt-capture-plugin.ts
  src/receipt-capture.ts
Labels: feature

#264 Fix/ios/rsp files
  example/src/app.vue
  ios/Plugin/Account.swift
  ios/Plugin/AccountCommon.swift
  ios/Plugin/AccountTypeEnum.swift
  ios/Plugin/Email.swift
  ios/Plugin/EmailEnum.swift
  ios/Plugin/Physical.swift
  ios/Plugin/ReceiptCapture.swift
  ios/Plugin/ReceiptCapturePlugin.m
  ios/Plugin/Req/ReqInitialize‎.swift
  ios/Plugin/Req/ReqLogin.swift
  ios/Plugin/Req/ReqLogout.swift
  ios/Plugin/Req/ReqRetailerLogin.swift
  ios/Plugin/Retailer.swift
  ios/Plugin/RetailerEnum.swift
  ios/Plugin/Rsp/Rsp.swift
  ios/Plugin/Rsp/RspAccount.swift
  ios/Plugin/Rsp/RspAccountList.swift
  ios/Plugin/Rsp/RspAdditionalLine.swift
  ios/Plugin/Rsp/RspCoupon.swift
  ios/Plugin/Rsp/RspFloatType.swift
  ios/Plugin/Rsp/RspInitialized.swift
  ios/Plugin/Rsp/RspPaymentMethod.swift
  ios/Plugin/Rsp/RspProduct.swift
  ios/Plugin/Rsp/RspPromotion.swift
  ios/Plugin/Rsp/RspReceipt.swift
  ios/Plugin/Rsp/RspScan.swift
  ios/Plugin/Rsp/RspShipment.swift
  ios/Plugin/Rsp/RspStringType.swift
  ios/Plugin/Rsp/RspSurveyAnswer.swift
  ios/Plugin/Rsp/RspSurveyQuestion.swift
  ios/Plugin/Rsp/RspSurveyResponse.swift
  ios/Plugin/ScanResultsDelegate.swift
Labels: fix

#299 Fix Email and Rsp
  ios/Plugin/AccountCommon.swift
  ios/Plugin/EmailEnum.swift
  ios/Plugin/Rsp/RspReceipt.swift
Labels: fix

#307 Feat/implement local notification
  android/src/main/AndroidManifest.xml
  example/android/app/capacitor.build.gradle
  example/android/app/src/main/AndroidManifest.xml
  example/android/capacitor.settings.gradle
  example/package-lock.json
  example/package.json
  example/src/main.ts
  package-lock.json
  package.json
  src/receipt-capture-plugin.ts
  src/receipt-capture-web.ts
  src/receipt-capture.ts
Labels: feature
